const express=require('express')
const router=express.Router()
const{sendOtp,otpMobile, otpEmail, panVerify,bankVerify,gstVerify, fetchAddress,bankDetails, adharVerify}=require('../utils/utils')
const{registerUser}=require('../control/control')
router.route('/register').post(sendOtp)
router.route('/otpverify').post(otpMobile)
router.route('/otpemail').post(otpEmail)
router.route('/adharverify').post(adharVerify)
router.route('/panverify').post(panVerify)
router.route('/verifybank').post(bankVerify)
router.route('/bankdetails/:id').get(bankDetails)
router.route('/gstverify').post(gstVerify)
router.route('/addresslookup').post(fetchAddress)
router.route('/submit').post(registerUser)
module.exports=router
